title: Sean "Gnagzs" Zhang Website
author: Sean Zhang
email: szhang120@mgmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Website

# social links
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-tactile
